{
 "title": "Syslog Overview",
 "tags": [ "syslog" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(job=\"syslog\", host)"
   },
   {
    "name": "filter",
    "label": "Filter",
    "query": "ERR,error,info,DEBUG,wpa_auth_failures,auth_failures"
   },
   { "name": "free_form_filter", "label": "Free Form Filter" },
   { "name": "smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h,2h" }
  ]
 },
 "panels": [
  {
   "title": "Logs (Counts - All)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Counts ($host) - $filter - $free_form_filter",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({host=~\"$host\", job=\"syslog\"} [$__interval] |~ \"$free_form_filter\" |~ \"$filter\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Logs - $host | $filter | $free_form_filter",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=~\"$host\"} |~ \"$free_form_filter\" |~ \"$filter\""
    }
   ]
  }
 ]
}