{
 "title": "Syslog Overview",
 "tags": [ "syslog" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(job=\"syslog\", host)"
   },
   {
    "name": "filter",
    "label": "Filter",
    "query": "info,debug,warn,error,ERR,DNS,auth_failures,wpa_auth_failures"
   },
   { "name": "free_form_filter", "label": "Free Form Filter" },
   { "name": "smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h,2h" }
  ]
 },
 "panels": [
  {
   "title": "Log Line Counts By Host (Unfiltered)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Info, Warn, Error, Debug (Unfiltered)",
   "type": "grafana-piechart-panel",
   "description": "Counts of log lines containing status listed.",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"syslog\"}  |~\"error\" [$__interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count_over_time({job=\"syslog\"}  |~\"info\" [$__interval]))",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(count_over_time({job=\"syslog\"}  |~\"warn\" [$__interval]))",
     "legendFormat": "Warn"
    },
    {
     "expr": "sum(count_over_time({job=\"syslog\"}  |~\"debug\" [$__interval]))",
     "legendFormat": "Debug"
    },
    {
     "expr": "sum(count_over_time({job=\"syslog\"}  !~\"debug\" !~\"warn\" !~\"info\" !~\"error\" [$__interval]))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Counts By Host ($host) - \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({host=~\"$host\", job=\"syslog\"} [$__interval] |~ \"$free_form_filter\" |~ \"$filter\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Logs By Host - \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"syslog\", host=~\"$host\"} |~ \"$free_form_filter\" |~ \"$filter\""
    }
   ]
  }
 ]
}